<script context="module">
  export async function preload(page, session) {
    let {path} = page.params;
    let result = await this.fetch(`/api/${path.join('/')}/report.json`);
    let report = await result.json();
    return {report};
  }
</script>

<script>
  // TODO: this could be a TS script once this Sapper issue is closed:
  // https://github.com/sveltejs/sapper/pull/1222
  export let report;
  import Report from "../../components/Report.svelte";
</script>

<title>ranked.vote: {report.info.jurisdictionName} / {report.info.name} / {report.info.date.substr(0, 4)}</title>

<div class="wide container">
<Report {report} />
<hr />
<div class="row"><p style="font-style: italic;">
  This report was generated by <a href="https://ranked.vote/">ranked.vote</a>
  and may be reproduced under <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>.
  Learn more <a href="https://ranked.vote/about">about ranked.vote</a>.
</p></div>
</div>