<script>
    /** @type {import('./$types').PageData} */
    export let data
    let report = data.report
    let path = data.path
  import Report from "../../../components/Report.svelte";
</script>

<svelte:head>
<title>approval.vote: {report.info.jurisdictionName} / {report.info.name} / {report.info.date.substr(0, 4)}</title>

  <meta property="og:title" content="{report.info.jurisdictionName} / {report.info.name}" />
  <meta property="og:image" content={"https://r.moxy.social/ykZcSLKZUq/approval/fb.png/" + path} />
  <meta property="twitter:card" content="summary_large_image" />
  <meta property="twitter:creator" content="@paulgb" />
  <meta property="twitter:title" content="{report.info.jurisdictionName} / {report.info.name}" />
  <meta property="twitter:image" content={"https://r.moxy.social/ykZcSLKZUq/approval/twitter.png/" + path} />
</svelte:head>

<div class="wide container">
<Report {report} />
<hr />
<div class="row"><p style="font-style: italic;">
  This report was generated by <a href="https://approval.vote/">approval.vote</a>
  and may be reproduced under <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>.
  Learn more <a href="https://approval.vote/about">about approval.vote</a>.
</p></div>
</div>

<a style="display:none;" href={"/card/" + path}>card</a>